### PR TITLE
Initial implementation of Noordhoff client/server

### PR DESCRIPTION
**Pull request by hhaarsma**
Initial implementation of Noordhoff client/server

### CODE REVIEW

**Review by cliftonc — APPROVED** [review]

**Comment by dpronk** [comment]
I hope you don’t expect me to do a review of this massive PR / Merge into Master before 13:00 today ….

Kind regards

Danny

**Comment by cliftonc** [comment]
No, not at all - it's us open sourcing our implementation - so no need for review.

**Comment by mcginkel** [comment]
Can we move this to another folder? Why is this suddenly the "implementation"? 
Can we make sub folders with "possible implementations"?

**Comment by cliftonc** [comment]
Well, it is the implementation of the LA services in the prototype?  This isn't 'THE' implementation (if there is such a thing outside of each participant anyway).

**Pull request merged**
